{
 "title": "1 - PowerFlex - Cluster",
 "tags": [ "PowerFlex" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CLU",
    "label": "Cluster",
    "query": {
     "query": "label_values(system_num_sds, clu_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Read OPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_read_total_iops{clu_name=\"$CLU\"}"
    }
   ]
  },
  {
   "title": "Write OPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_write_total_iops{clu_name=\"$CLU\"} / 2"
    }
   ]
  },
  {
   "title": "Read Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_read_total_kb{clu_name=\"$CLU\"}"
    }
   ]
  },
  {
   "title": "Write Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_write_total_kb{clu_name=\"$CLU\"} / 2"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "system_read_total_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Read Ops"
    },
    {
     "expr": "system_write_total_iops{clu_name=\"$CLU\"} / 2",
     "legendFormat": "Write Ops"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "system_read_total_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Read bw"
    },
    {
     "expr": "system_write_total_kb{clu_name=\"$CLU\"} / 2",
     "legendFormat": "Write bw"
    }
   ]
  },
  {
   "title": "Top 10 SDC's Read OPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "topk(10, avg(sdc_read_user_data_iops{clu_name=\"$CLU\"}) BY (sdc_name))",
     "legendFormat": "{{sdc_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDC's Write OPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "topk(10, avg(sdc_write_user_data_iops{clu_name=\"$CLU\"}) BY (sdc_name))",
     "legendFormat": "{{sdc_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDC's Read Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(sdc_read_user_data_kb{clu_name=\"$CLU\"}) BY (sdc_name))",
     "legendFormat": "{{sdc_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDC's Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(sdc_write_user_data_kb{clu_name=\"$CLU\"}) BY (sdc_name))",
     "legendFormat": "{{sdc_name}}"
    }
   ]
  },
  {
   "title": "Max Pool's Read Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(device_read_latency_ms{clu_name=\"$CLU\"}) by (sto_name,pdo_name)",
     "legendFormat": "{{pdo_name}} / {{sto_name}}"
    }
   ]
  },
  {
   "title": "Max Pool's Write Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(device_write_latency_ms{clu_name=\"$CLU\"}) by (sto_name,pdo_name)",
     "legendFormat": "{{pdo_name}} / {{sto_name}}"
    }
   ]
  },
  {
   "title": "Forward Rebuild IOPs/Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "system_read_fwd_rebuild_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Read ops"
    },
    {
     "expr": "system_write_fwd_rebuild_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Write ops"
    },
    {
     "expr": "system_read_fwd_rebuild_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Read bw"
    },
    {
     "expr": "system_write_fwd_rebuild_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Write bw"
    }
   ]
  },
  {
   "title": "Backward Rebuild IOPs/Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "system_read_bck_rebuild_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Read ops"
    },
    {
     "expr": "system_write_bck_rebuild_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Write ops"
    },
    {
     "expr": "system_read_bck_rebuild_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Read bw"
    },
    {
     "expr": "system_write_bck_rebuild_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Write bw"
    }
   ]
  },
  {
   "title": "Rebalance IOPs/Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "system_read_rebalance_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Read ops"
    },
    {
     "expr": "system_write_rebalance_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Write ops"
    },
    {
     "expr": "system_read_rebalance_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Read bw"
    },
    {
     "expr": "system_write_rebalance_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Write bw"
    }
   ]
  }
 ]
}