{
 "title": "3 - PowerFlex - Storage Pools",
 "tags": [ "PowerFlex" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CLU",
    "label": "Cluster",
    "query": {
     "query": "label_values(storagepool_num_devices, clu_name)"
    }
   },
   {
    "name": "DOMAIN",
    "label": "Protection Domain",
    "query": {
     "query": "label_values(storagepool_num_devices{clu_name=\"$CLU\"}, pdo_name)"
    }
   },
   {
    "name": "POOL",
    "label": "Storage Pool",
    "query": {
     "query": "label_values(storagepool_num_devices{clu_name=\"$CLU\", pdo_name=\"$DOMAIN\"}, sto_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Allocation",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storagepool_capacity_use_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2",
     "legendFormat": "Used Capacity"
    },
    {
     "expr": "storagepool_capacity_unused_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2",
     "legendFormat": "Free Capacity"
    }
   ]
  },
  {
   "title": "Storage Pool Capacities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "storagepool_capacity_failed_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2",
     "legendFormat": "failed"
    },
    {
     "expr": "storagepool_capacity_moving_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2",
     "legendFormat": "moving"
    },
    {
     "expr": "storagepool_capacity_protected_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2",
     "legendFormat": "protected"
    },
    {
     "expr": "storagepool_capacity_spare_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2",
     "legendFormat": "spare"
    },
    {
     "expr": "storagepool_capacity_unused_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2",
     "legendFormat": "unused"
    },
    {
     "expr": "storagepool_capacity_use_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2",
     "legendFormat": "use"
    }
   ]
  },
  {
   "title": "Read OPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storagepool_read_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}"
    }
   ]
  },
  {
   "title": "Write OPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "storagepool_write_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2"
    }
   ]
  },
  {
   "title": "Read Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "storagepool_read_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}"
    }
   ]
  },
  {
   "title": "Write Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "storagepool_write_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "storagepool_read_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "Read ops"
    },
    {
     "expr": "storagepool_write_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2",
     "legendFormat": "Write ops"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "storagepool_read_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "Read bw"
    },
    {
     "expr": "storagepool_write_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"} / 2",
     "legendFormat": "Write bw"
    }
   ]
  },
  {
   "title": "Top 10 Volume Read OPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "topk(10, avg(volume_read_user_data_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) BY (vol_name))",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Volume Write OPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "topk(10, avg(volume_write_user_data_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) BY (vol_name))",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Volume Read Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(volume_read_user_data_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) BY (vol_name))",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Volume Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(volume_write_user_data_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) BY (vol_name))",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDS Read OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "topk(10, avg(sds_read_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\"}) BY (sds_name))",
     "legendFormat": "{{sds_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDS Write OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "topk(10, avg(sds_write_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\"}) BY (sds_name))",
     "legendFormat": "{{sds_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDS Read Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(sds_read_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\"}) BY (sds_name))",
     "legendFormat": "{{sds_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDS Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(sds_write_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\"}) BY (sds_name))",
     "legendFormat": "{{sds_name}}"
    }
   ]
  },
  {
   "title": "Max Pool SDS Read Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(device_read_latency_ms{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) by (sds_name)",
     "legendFormat": "{{sds_name}}"
    }
   ]
  },
  {
   "title": "Max Pool SDS Write Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(device_write_latency_ms{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) by (sds_name)",
     "legendFormat": "{{sds_name}}"
    }
   ]
  }
 ]
}