{
 "title": "4 - PowerFlex - Volumes",
 "tags": [ "PowerFlex" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CLU",
    "label": "Cluster",
    "query": {
     "query": "label_values(volume_read_user_data_iops, clu_name)"
    }
   },
   {
    "name": "DOMAIN",
    "label": "Protection Domain",
    "query": {
     "query": "label_values(volume_read_user_data_iops{clu_name=\"$CLU\"}, pdo_name)"
    }
   },
   {
    "name": "POOL",
    "label": "Storage Pool",
    "query": {
     "query": "label_values(volume_read_user_data_iops{clu_name=\"$CLU\", pdo_name=\"$DOMAIN\"}, sto_name)"
    }
   },
   {
    "name": "VOL",
    "label": "Volume",
    "query": {
     "query": "label_values(volume_read_user_data_iops{clu_name=\"$CLU\", pdo_name=\"$DOMAIN\", sto_id=\"$POOL_ID\"}, vol_name)"
    }
   },
   {
    "name": "VOL_ID",
    "query": {
     "query": "label_values(volume_read_user_data_iops{clu_name=\"$CLU\", pdo_name=\"$DOMAIN\", sto_name=\"$POOL\"}, vol_id)"
    }
   },
   {
    "name": "POOL_ID",
    "query": {
     "query": "label_values(volume_read_user_data_iops{clu_name=\"$CLU\", pdo_name=\"$DOMAIN\"}, sto_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Read OPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volume_read_user_data_iops{vol_name=\"$VOL\"}"
    }
   ]
  },
  {
   "title": "Write OPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volume_write_user_data_iops{vol_name=\"$VOL\"}"
    }
   ]
  },
  {
   "title": "Read Bandwidth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volume_read_user_data_kb{vol_name=\"$VOL\"}"
    }
   ]
  },
  {
   "title": "Write Bandwidth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volume_write_user_data_kb{vol_name=\"$VOL\"}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "volume_read_user_data_iops{vol_name=\"$VOL\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "volume_write_user_data_iops{vol_name=\"$VOL\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "volume_read_user_data_kb{vol_name=\"$VOL\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "volume_write_user_data_kb{vol_name=\"$VOL\"}",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}